import type { EnemyDef } from '../types';

/**
 * Everything is a black silhouette with a coloured rim and glowing eyes. The rim
 * colour is the player's only read on what a shape does, so each behaviour owns
 * a hue and never shares it.
 */
export const ENEMIES: EnemyDef[] = [
  {
    id: 'crawler',
    name: 'Crawler',
    hp: 10,
    speed: 46,
    dmg: 7,
    r: 11,
    xp: 1,
    rim: '#3d4a5a',
    eyes: 2,
    behaviour: 'chase',
    from: 0,
    weight: 100,
  },
  {
    id: 'wretch',
    name: 'Wretch',
    hp: 7,
    speed: 88,
    dmg: 5,
    r: 8.5,
    xp: 1,
    rim: '#6b8f5a',
    eyes: 2,
    behaviour: 'dart',
    from: 18,
    weight: 78,
  },
  {
    id: 'bloater',
    name: 'Bloater',
    hp: 44,
    speed: 30,
    dmg: 15,
    r: 18,
    xp: 3,
    rim: '#8a6a3d',
    eyes: 1,
    behaviour: 'chase',
    from: 34,
    weight: 40,
  },
  {
    id: 'stalker',
    name: 'Stalker',
    hp: 20,
    speed: 74,
    dmg: 10,
    r: 12,
    xp: 2,
    rim: '#7a5aa0',
    eyes: 4,
    behaviour: 'drift',
    from: 52,
    weight: 52,
  },
  {
    id: 'weaver',
    name: 'Weaver',
    hp: 26,
    speed: 34,
    dmg: 9,
    r: 13,
    xp: 3,
    rim: '#b1263a',
    eyes: 6,
    behaviour: 'ranged',
    from: 74,
    weight: 34,
  },
  {
    id: 'lurker',
    name: 'Lurker',
    hp: 32,
    speed: 40,
    dmg: 13,
    r: 13,
    xp: 3,
    rim: '#2f7f7a',
    eyes: 3,
    behaviour: 'blink',
    from: 100,
    weight: 30,
  },
  {
    id: 'husk',
    name: 'Husk',
    hp: 130,
    speed: 21,
    dmg: 20,
    r: 24,
    xp: 6,
    rim: '#5a5f68',
    eyes: 2,
    behaviour: 'wall',
    from: 128,
    weight: 22,
  },
  {
    id: 'shade',
    name: 'Shade',
    hp: 30,
    speed: 96,
    dmg: 12,
    r: 11,
    xp: 4,
    rim: '#9aa4b0',
    eyes: 0,
    behaviour: 'flicker',
    from: 155,
    weight: 26,
  },
];

export const enemyById = (id: string): EnemyDef => ENEMIES.find((e) => e.id === id) ?? ENEMIES[0];
